version: 0.2
phases:
  pre_build:
    commands:
      - ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
      - REGISTRY=${ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com
      - aws ecr get-login-password | docker login --username AWS --password-stdin ${REGISTRY}
  build:
    commands:
      - docker build --pull -f Dockerfile.agent -t ${REGISTRY}/launchpad-agent:${IMAGE_TAG} .
      - docker push ${REGISTRY}/launchpad-agent:${IMAGE_TAG}
